name: Sociology Daily Bot

on:
  workflow_dispatch:

jobs:
  run-bot:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python sociology.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL: ${{ secrets.CHANNEL }}
